# Generated by Django 4.2.4 on 2023-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
